[env:lolin32_lite_simple]
platform = espressif32
board = lolin32_lite
framework = arduino

; Only compile the main file and DRV8825 library
build_src_filter = 
  +<main_simple.cpp>
  +<DRV8825>

; Monitor settings
monitor_speed = 115200

; Upload settings
upload_port = COM9
monitor_port = COM9

; Only include DRV8825 library
lib_deps =
